VEX_DIR=/home/aaron/documents/binary/bitblaze/vine-build/vine-1/VEX/
LIBASMIR_CXXFLAGS=-I/home/aaron/documents/binary/bitblaze/vine-build/vine-1/VEX//pub -I/home/aaron/documents/binary/bitblaze/vine-build/vine-1/src/include -g -O2
LIBASMIR_LDFLAGS=-L/home/aaron/documents/binary/bitblaze/vine-build/vine-1/VEX/ -L/home/aaron/documents/binary/bitblaze/vine-build/vine-1/src 
LIBASMIR_LIBS=-lasmir -lvex -lbfd -liberty
